services:
  - type: web
    name: canal-informatique
    runtime: python
    rootDir: backend_python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: RESEND_API_KEY
        sync: false
      - key: TARGET_EMAIL
        sync: false
    healthCheckPath: /api/health
